version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-23-21-156-171.compute-1.amazonaws.com
            database: dbd8kgg8dpvlnr
            schema: public
            user: knecsgelujosbc
            password: 1a385dd111253e47c91492d2565851d2fa4bd59bf19480b71ca87f8d64a301a6
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true